name: Test and build package
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn lint
      - run: yarn prettier
      - run: yarn test
      - run: yarn build
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3